### ISSUE TITLE
Make error great

### ISSUE THREAD

**Issue by Et7f3** [TheNaturLFoundation/naturL#5]
**Describe the bug**
The error message can be enhanced

**To Reproduce**
`echo -ne "fonction a()->entier\ndebut\nretourner 1\nfin" | ./naturL.exe`
`Syntax error at line 2: Expected '->', got '>entier'` line 2 ?

**Expected behavior**
Error line 1 ? and maybe display a tips: you need to put space around `->` or allow it in the syntax.

**Desktop (please complete the following information):**
 - OS: unrelevant
 - Version: master

**Comment by RostanTabet** [comment]
Thank you for reporting this issue
