### ISSUE TITLE
Tabs and useless space forbidden

### ISSUE THREAD

**Issue by Et7f3** [TheNaturLFoundation/naturL#6]
**Describe the bug**
Tabs are forbidden. And space between parenthesis are forbidden: maybe this is wanted. Having tabs forbidden is annoying because some editor save with tabs.

**To Reproduce**
`echo -ne "fonction a( ) -> entier\ndebut\n\tretourner 1\nfin" | ./naturL.exe`

**Expected behavior**
Tabs should be allowed. and `( )` might be allowed. Also the carriage return `\r` in the windows EOL style `\r\n` is not handled.

**Desktop (please complete the following information):**
 - OS: unrelevant
 - Version: master

**Comment by RostanTabet** [comment]
Thanks for reporting this issue. It now should be fixed.

**Comment by Et7f3** [comment]
Does it handle: `fonction a( entier  g,entier d )` ?
